package schema

import (
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// migrationOnlyTables are the tables a numbered migration creates, which the
// baseline DDL therefore does not declare.
//
// THIS IS NOT A LIST OF BUGS, and the difference matters because it is easy to
// read it as one. A missing CREATE TABLE does not make a fresh install diverge
// from a migrated one: migrate() applies the baseline AND then runs every
// versioned migration, on every open, so both kinds of database end up with
// these tables either way. TestSchemaConvergesAcrossVintages proves that
// property directly, by upgrading an old database and diffing it against a new
// one.
//
// The baseline was frozen at a point in time; everything since arrived as a
// migration. That is the normal shape of this schema, not an accident that
// happened seventeen times.
//
// What the list is for is the NEXT table. Adding one to a migration is fine;
// adding one without noticing which half of the schema it landed in is how a
// reader ends up consulting the constants file and getting an incomplete
// answer. Failing here makes that a decision instead of a side effect.
var migrationOnlyTables = map[string]string{
	"schema_migrations":         "the migration runner's own bookkeeping — it has to exist before a migration can record itself",
	"bin_loader_home_bin_types": "added by v75 — what each loader window can physically take",
	"bin_loader_homes":          "added by a numbered migration after the baseline was frozen",
	"bin_loader_quotas":         "added by v75 — a loader's declared carrier mix",
	"bin_loader_payloads":       "added by a numbered migration after the baseline was frozen",
	"bin_loaders":               "added by a numbered migration after the baseline was frozen",
	"bin_uop_audit":             "added by a numbered migration after the baseline was frozen",
	"cell_config":               "added by a numbered migration after the baseline was frozen",
	"demand_origins":            "added by a numbered migration after the baseline was frozen",
	"edge_cells":                "added by a numbered migration after the baseline was frozen",
	"edge_lineside_reports":     "added by a numbered migration after the baseline was frozen",
	"order_bins":                "added by a numbered migration after the baseline was frozen",
	"pending_restocks":          "added by a numbered migration after the baseline was frozen",
	"process_styles":            "added by a numbered migration after the baseline was frozen",
	"reservations":              "added by a numbered migration after the baseline was frozen",
	"sourceability_events":      "added by a numbered migration after the baseline was frozen",
	"style_claims":              "added by a numbered migration after the baseline was frozen",
	"supply_refusals":           "added by a numbered migration after the baseline was frozen",
}

// TestBaselineDDL_DeclaresEveryTable pins which half of the schema each table
// lives in: declared in the baseline DDL, or named above as migration-created.
//
// The snapshot is the authority for what actually ships — it is generated by
// running the real migrate path against an empty database. A table in the
// snapshot that is in neither the baseline nor the list above is one nobody
// decided about.
func TestBaselineDDL_DeclaresEveryTable(t *testing.T) {
	t.Parallel()
	declared := ddlTables(t)
	shipped := snapshotTables(t)

	if len(shipped) == 0 {
		t.Fatal("parsed zero tables out of the snapshot; the parser is broken, not the schema")
	}

	var missing []string
	for _, tbl := range shipped {
		if declared[tbl] {
			continue
		}
		if _, ok := migrationOnlyTables[tbl]; ok {
			continue
		}
		missing = append(missing, tbl)
	}
	if len(missing) > 0 {
		t.Errorf("tables in the shipped schema that are in neither the baseline DDL nor migrationOnlyTables: %s\n"+
			"Say which half it belongs to: add the CREATE TABLE to postgres_ddl.go, or add the table to migrationOnlyTables naming what creates it.\n"+
			"Either is fine. Not choosing is what this test is here to catch.",
			strings.Join(missing, ", "))
	}

	// The allowlist decays too: an entry naming a table that the baseline has
	// since declared is a claim about the past.
	for tbl := range migrationOnlyTables {
		if declared[tbl] {
			t.Errorf("migrationOnlyTables names %q, but the baseline DDL now declares it — drop the entry", tbl)
		}
	}
}

var (
	ddlTableRe      = regexp.MustCompile(`(?m)^CREATE TABLE IF NOT EXISTS\s+(\w+)`)
	snapshotTableRe = regexp.MustCompile(`(?m)^CREATE TABLE public\.(\w+)`)
)

// ddlTables returns the table names declared in the baseline DDL constant.
func ddlTables(t *testing.T) map[string]bool {
	t.Helper()
	out := map[string]bool{}
	for _, m := range ddlTableRe.FindAllStringSubmatch(postgresDDL, -1) {
		out[m[1]] = true
	}
	if len(out) == 0 {
		t.Fatal("parsed zero tables out of postgresDDL; the parser is broken, not the constant")
	}
	return out
}

// snapshotTables returns the table names in the committed schema snapshot,
// sorted, excluding partitions of declaratively partitioned tables (those are
// created per-range by the partition machinery, not declared).
func snapshotTables(t *testing.T) []string {
	t.Helper()
	const path = "schema.snapshot.sql"
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	seen := map[string]bool{}
	for _, m := range snapshotTableRe.FindAllStringSubmatch(string(b), -1) {
		seen[m[1]] = true
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
